id: eote-talent-bypass-security
name: Bypass Security
description: Remove <setback></setback> per rank of Bypass Security from checks made to disable a security device or
  open a locked door.
activation: p
ranked: true
forceTalent: false
trees: Skip Tracer, Sleeper Agent, Slicer, Thief
reference:
  - E-CRB:133
  - A-CRB:144
